
name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: Send email notification
        if: ${{ success() }}
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com 
          server_port: 587  
          username: ssanthosh2k3@gmail.com
          password: updj lldw hfuf nqgv
          subject: 'Pipeline execution successful'
          body: 'Your pipeline has executed .'
          to: 'santhoshsh2326@gmail.com'
          from: 'ssanthosh2k3@gmail.com'
