name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: Send email notification
        if: ${{ success() }}
        uses: dawidd6/action-send-mail@v2
        with:
          username: ssanthosh2k3@gmail.com
          password: gigachad@4323
          subject: 'Pipeline execution successful'
          body: 'Your pipeline has executed successfully.'
          to: 'gunavelraj23@gmail.com'
          from: 'ssanthosh2k3@gmail.com'
