name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Add your build steps here, such as compiling code, running tests, etc.

  approval:
    name: Wait for Approval
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' # Only proceed for main branch

    steps:
      - name: Wait for approval
        id: approval
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:owner/:repo/pulls/:pull_number
          pull_number: ${{ github.event.pull_request.number }}
          headers:
            Authorization: ${{ secrets.GITHUB_TOKEN }}

      - name: Send approval notification email
        if: steps.approval.outputs.data.labels[0].name == 'approved'
        uses: sendgrid/email-action@v1.2.0
        with:
          from_email: your@email.com
          to_email: recipient@email.com
          subject: Pull Request Approved
          text: The pull request has been approved and is ready for deployment.

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: approval
    if: github.event_name == 'pull_request' && steps.approval.outputs.data.labels[0].name == 'approved'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}  # Replace with the secret name where your server IP is stored
          username: ${{ secrets.SERVER_USERNAME }}  # Replace with the secret name where your server username is stored
          key: ${{ secrets.SERVER_SSH_KEY }}  # Replace with the secret name where your SSH private key is stored
          script: |
            cd /path/to/remote/root/directory  # Replace with your remote root directory path
            git pull origin main  # Or any other command needed to deploy your application

# Replace placeholders below with actual secret values in your GitHub repository settings
secrets:
  GITHUB_TOKEN: your-github-token
  SERVER_IP: your-server-ip
  SERVER_USERNAME: your-server-username
  SERVER_SSH_KEY: your-server-ssh-private-key
