name: Deploy Website

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to production server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.54.161.109.32 }}  # 54.161.109.32 eplace with your production server's hostname or IP address
        username: ${{ ubuntu }}  # Replace with your username on the production server
        key: ${{ secrets.PRODUCTION_SSH }}  # Replace with your SSH private key for accessing the production server
        source: "LED.txt"  # Adjust this to the directory where your HTML files reside
        target: "/var/www/html"  # Adjust this to the directory on your production server where you want to deploy the website
